export const ROLES = {
  SUPER_ADMIN: "ROLE_SUPER_ADMIN",
  ADMIN: "ROLE_ADMIN",
  RH_MANAGER: "ROLE_RH_MANAGER",
  DG: "ROLE_DIRECTEUR_GENERAL",
  RH_ASSITANT: "ROLE_ASSISTANT_RH",
  CHEF_SERVICE: "ROLE_CHEF_DE_SERVICE",
  EMPLOYE: "ROLE_EMPLOYE",
  COMPTABLE: "ROLE_COMPTABLE",
};

// Which roles can access which modules
export const MODULE_ACCESS = {
  m1_employees: [
    ROLES.SUPER_ADMIN,
    ROLES.RH_MANAGER,
    ROLES.RH_ASSITANT,
    ROLES.DG,
  ],
  m2_leaves: [
    ROLES.SUPER_ADMIN,
    ROLES.RH_MANAGER,
    ROLES.RH_ASSITANT,
    ROLES.CHEF_SERVICE,
    ROLES.EMPLOYE,
    ROLES.DG,
  ],
  m3_payroll: [
    ROLES.SUPER_ADMIN,
    ROLES.RH_MANAGER,
    ROLES.RH_ASSITANT,
    ROLES.COMPTABLE,
    ROLES.DG,
  ],
  m4_contracts: [
    ROLES.SUPER_ADMIN,
    ROLES.RH_MANAGER,
    ROLES.RH_ASSITANT,
    ROLES.DG,
  ],
};
